# Generated by Django 4.2.27 on 2025-12-21 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='update_on',
            new_name='updated_on',
        ),
    ]
